### ISSUE TITLE
NSML nsml_package 설치관련 문의

### ISSUE THREAD

**Issue by HongJinSeong** [DatathonInfo/SOChallenge#10]
mmdetection 라이브러리를 설치하여 사용하려고 하는데 아래의 2가지 추가 설치 라이브러리가 있어서

libgl1-mesa-glx
libglib2.0-0

를 추가로 apt-get 명령어로 설치하려고하였습니다.

nsml 가이드에 따라서  nsml_package.txt 파일을 만들어서 설치하려고 하는데 다음과 같은 에러가 발생합니다.

Step 10/13 : RUN python -mplatform | egrep -qi "Ubuntu|Debian" && (apt-get -q -o=Dpkg::Use-Pty=0 -y update && apt-get -q -o=Dpkg::Use-Pty=0 -y install libgl1-mesa-glx libglib2.0-0) || (yum install -q -y libgl1-mesa-glx libglib2.0-0)
 ---> Running in b4a866cf5315
[91m/bin/bash: yum: command not found
[0m
SOC009/CUBOX_SOC/82: Fail to build session
Warning: SOC009/CUBOX_SOC/82 is already removed. It will be removed from nsml soon

![image](https://user-images.githubusercontent.com/47050422/144360734-e79112db-4aee-4b28-aca6-6957e2b97670.png)

**Comment by DatathonInfo** [comment]
안녕하세요 참가자님,

SOC Baseline에서 제공해드린 `setup.py`는 `nvcr.io/nvidia/pytorch:20.12-py3`를 베이스 이미지로 사용하고 있습니다.
해당 이미지는 NSML에서 제공하는 image가 아니기 때문에 `nsml_package.txt` 처리중 오류가 발생할 가능성이 높습니다.

가능하시다면 `setup.py`에서
NSML 기본 docker image인 `nsml/default_ml:latest`를 사용해 주시거나, 
mmdetection에 필요한 라이브러리가 설치된 docker image로 변경해 주시면 감사하겠습니다.

감사합니다.

**Comment by HongJinSeong** [comment]
답변감사합니다.
