### ISSUE TITLE
소형객체 모델개발 대회 규정 문의

### ISSUE THREAD

**Issue by wisetrue95** [DatathonInfo/SOChallenge#4]
이번 소형객체 AI모델 개발 track에 참여하였습니다.

몇가지 궁금한 사항이 있어 메일 드립니다.

1. 공개되어 있는 다른 object detection 깃허브 모델을 사용해도 되는지 궁금합니다.

2. 대회방식 및 규칙에 "훈련에 pretrained 모델(웨이트)는 쓸수 없습니다." 라고 나와있는데

만약 공개된 모델로 학습할 때 사전학습된 모델 웨이트 지정만 안하면 문제 없는건가요?

3. 현재 나와있는 평가지표는 mAP만 나와있는데 속도 측면은 고려하지 않는지 궁금합니다.

**Comment by DatathonInfo** [comment]
안녕하세요 참가자님,

1. pretrained weight를 load 하지 않는 오픈소스 모델은 사용이 가능합니다.

2. 대회규정 상 속도 측면은 평가하지 않고 있습니다. 다만 model submit시 인퍼런스는 1시간으로 제한되며, 초과시 점수 반영이 되지 않습니다. 또한 동점자 발생시 1)모델제출 순, 2)weight 파일 크기 순으로 평가됩니다.

감사합니다.
