### ISSUE TITLE
nsml 로그인 관련 문의

### ISSUE THREAD

**Issue by namho-96** [DatathonInfo/SOChallenge#7]
안녕하세요.
오늘 대회가 오픈된 후에 가이드대로 nsml에 로그인하였는데 
1. level=fatal msg="login failed: Authentication failure. Please login again."
2. level=fatal msg="login failed: Authentication failure. Please login again."
이런 메세지가 뜨면서 로그인이 안되고 있습니다.
바쁘실테지만 문제 관련하여 확인해주시면 감사드리겠습니다.

**Comment by DatathonInfo** [comment]
안녕하세요 참가자님,

Authentication failure 메시지가 나오는 경우, 비밀번호 오류이니
로그인 시 ID 및 PWD는 대/소문자를 구분하니, 다시 확인 부탁드리겠습니다.

감사합니다.

**Comment by namho-96** [comment]
빠른 답변 감사드립니다.
아이디 및 패스워드 확인하여 이제는 Authentication failure는 뜨지 않는데
level=fatal msg="login failed: Please wait a while and try again later"
라는 메세지가 뜹니다. 이 메세지는 어떤 오류인지 확인 가능할까요?
